name: Update Language Stats

on:
  schedule:
    # Corre todos los días a la medianoche UTC
    - cron: "0 0 * * *"

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configura el entorno de Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 3. Instala dependencias necesarias
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub pandas

      # 4. Ejecuta el script para calcular el uso de lenguajes
      - name: Run Script
        run: python update_stats.py

      # 5. Subir cambios al repositorio
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update language stats [skip ci]" || echo "No changes to commit"
          git push

